<a href="https://colab.research.google.com/github/mgodfrey1294/Numpy-Tutorial-Youtube/blob/main/Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Filtering Numpy Arrays with Boolean Index Lists
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

x = [True, True, False, False, False, False, False, False, False, False]

print(np1)
print(np1[x])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2]


In [5]:
filtered = []
for thing in np1:
  if thing % 2 == 0:
    filtered.append(True)
  else:
    filtered.append(False)

print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False, False, False, False, False, True, True, True, True, True]
[ 6  7  8  9 10]


In [6]:
# Shortcut!
filtered = np1 % 2 == 0
print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
