<a href="https://colab.research.google.com/github/mgodfrey1294/Numpy-Tutorial-Youtube/blob/main/Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [7]:
# Numpy Universal Function
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np1)

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]


In [8]:
# Square root of each element
print(np.sqrt(np1))

[       nan        nan        nan 0.         1.         1.41421356
 1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712
 3.        ]


<ipython-input-8-15bf2df1ab87>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))


In [9]:
# Absolute Value
print(np.absolute(np1))

[3 2 1 0 1 2 3 4 5 6 7 8 9]


In [10]:
# Exponents
print(np.exp(np1))

[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [11]:
# Min/Max
print(np.max(np1))
print(np.min(np1))

9
-3


In [12]:
# Sign positive or negative
print(np.sign(np1))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


In [14]:
# Trig sin cos log
print(np.sin(np1))
print(np.log(np1))

[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]
[       nan        nan        nan       -inf 0.         0.69314718
 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154
 2.19722458]


<ipython-input-14-aa94c97f98b7>:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
<ipython-input-14-aa94c97f98b7>:3: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))
