<a href="https://colab.research.google.com/github/mgodfrey1294/Numpy-Tutorial-Youtube/blob/main/Iterate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# 1-d
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np1:
  print(x)

1
2
3
4
5
6
7
8
9
10


In [5]:
# 2-d Array
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np2:
  # Print rows
  print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [6]:
for x in np2:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10


In [11]:
# 3-D Array
np3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
for x in np3:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [12]:
for x in np3:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [13]:
for x in np3:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [14]:
# Use np.nditer
for x in np.nditer(np3):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [16]:
for x in np.nditer(np1):
  print(x)

1
2
3
4
5
6
7
8
9
10
