<a href="https://colab.research.google.com/github/mgodfrey1294/Numpy-Tutorial-Youtube/blob/main/Numpy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# List demo
list1 = [1,2,3,4,5]
print(list1)
print(list1[0])

[1, 2, 3, 4, 5]
1


In [ ]:
# You can store multiple datatypes in lists
list2 = ["John Elder", 41, list1, True]
print(list2)

['John Elder', 41, [1, 2, 3, 4, 5], True]


In [ ]:
import numpy as np

In [ ]:
# Numpy - Numeric Python
# ndarray = n-dimensional array

np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
# See the shape of the array - tells us the number of elements in the array - think of the len function for lists.
print(np1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [ ]:
# np.arange(n) creates an array starting at 0 and goes up to (not including) n
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Step
# np.arange(start, end, step)
# Start at 0, end at 10 (does not include it), add 2 each time
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]
