<a href="https://colab.research.google.com/github/mgodfrey1294/Numpy-Tutorial-Youtube/blob/main/Searcher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
# Search
np1 = np.array([1,2,3,4,5,6,7,8,9,10,3])

x = np.where(np1 == 3)
print(np1)
print(x[0])
print(np1[x[0]])

[ 1  2  3  4  5  6  7  8  9 10  3]
[ 2 10]
[3 3]


In [8]:
# Return even items
y = np.where(np1 % 2 == 0)
print(np1)
print(y[0])

[ 1  2  3  4  5  6  7  8  9 10  3]
[1 3 5 7 9]


In [9]:
# Return odd items
z = np.where(np1 % 2 == 1)
print(np1)
print(z[0])

[ 1  2  3  4  5  6  7  8  9 10  3]
[ 0  2  4  6  8 10]
