<a href="https://colab.research.google.com/github/mgodfrey1294/Numpy-Tutorial-Youtube/blob/main/Slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [12]:
# Slicing Numpy Arrays
np1 = np.array([1,2,3,4,5,6,7,8,9])

# Return 2,3,4,5
print(np1[1:5])

[2 3 4 5]


In [13]:
# Return from something until the end of the array?
# Return 4-9
print(np1[3:])

[4 5 6 7 8 9]


In [14]:
# Return Negative Slices
# 7, 8
print(np1[-3:-1])

[7 8]


In [15]:
# Steps
print(np1[1:5]) # 2-5
print(np1[1:5:2]) # 2-5 in steps of 2

[2 3 4 5]
[2 4]


In [16]:
# Steps on the entire array
print(np1[::2])

[1 3 5 7 9]


In [17]:
print(np1[::3])

[1 4 7]


In [18]:
# Slice a 2-d array
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# [[1,2,3,4,5],
#  [6,7,8,9,10]]
# Pull out a single item
print(np2[1,2])

8


In [19]:
# Slice a 2-d array 2,3
print(np2[0:1, 1:3])

[[2 3]]


In [20]:
# Slice from both rows 2,3 and 7,8
print(np2[0:2, 1:3])

[[2 3]
 [7 8]]
